# Generated by Django 5.1 on 2024-08-21 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('text', models.TextField(verbose_name='Текст рекламы')),
                ('responses', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество откликов')),
            ],
            options={
                'verbose_name': 'Реклама',
                'verbose_name_plural': 'Реклама',
            },
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Пользовательский торт', max_length=100, verbose_name='Название')),
                ('levels_number', models.SmallIntegerField(choices=[(1, '1 уровень'), (2, '2 уровня'), (3, '3 уровня')], verbose_name='Количество уровней')),
                ('shape', models.CharField(choices=[('square', 'квадрат'), ('circle', 'круг'), ('rectangle', 'прямоугольник')], max_length=50, verbose_name='Форма')),
                ('topping', models.CharField(choices=[('no_topping', 'без топпинга'), ('white_sauce', 'белый соус'), ('caramel_syrup', 'карамельный сироп'), ('maple_syrup', 'кленовый сироп'), ('strawberry_syrup', 'клубничный сироп'), ('blueberry_syrup', 'черничный сироп'), ('milk_chocolate', 'молочный шоколад')], max_length=50, verbose_name='Топпинг')),
                ('berries', models.CharField(blank=True, choices=[('no_berries', 'без ягод'), ('blackberry', 'ежевика'), ('raspberries', 'малина'), ('blueberry', 'голубика'), ('strawberry', 'клубника')], max_length=50, null=True, verbose_name='Ягоды')),
                ('decor', models.CharField(blank=True, choices=[('no_decor', 'без декора'), ('pistachio', 'фисташки'), ('meringue', 'безе'), ('hazelnut', 'фундук'), ('pecan', 'пекан'), ('marshmallow', 'маршмеллоу'), ('marzipan', 'марципан')], max_length=50, null=True, verbose_name='Декор')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('is_base', models.BooleanField(default=False, verbose_name='Стандартный торт')),
            ],
            options={
                'verbose_name': 'Торт',
                'verbose_name_plural': 'Торты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='Время доставки')),
                ('inscription', models.CharField(blank=True, max_length=200, null=True, verbose_name='Надпись')),
                ('total_price', models.FloatField(blank=True, null=True, verbose_name='Конечная цена')),
                ('fast_delivery', models.BooleanField(default=False, verbose_name='Быстрая доставка')),
                ('cake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cake.cake', verbose_name='Торт')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
