# Generated by Django 5.1 on 2024-08-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='photo',
            field=models.ImageField(default='images/cakes/default_cake.png', upload_to='images/cakes', verbose_name='Фото'),
        ),
    ]
