# Generated by Django 5.1 on 2024-08-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0003_cake_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='reason',
            field=models.CharField(blank=True, choices=[('tea', 'чаепитие'), ('birthday', 'день рождения'), ('wedding', 'свадьба')], max_length=50, null=True, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='photo',
            field=models.ImageField(default='cakes/default_cake.png', upload_to='cakes/', verbose_name='Фото'),
        ),
    ]
