# Generated by Django 5.1 on 2024-08-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0004_cake_reason_alter_cake_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
