# Generated by Django 5.1 on 2024-08-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0005_alter_cake_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('payment', 'В оплате'), ('delivery', 'В доставке'), ('complete', 'Завершен')], default='payment', max_length=50, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='photo',
            field=models.ImageField(default='../static/cake/img/default_cake.png', upload_to='cakes/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='reason',
            field=models.CharField(blank=True, choices=[('tea', 'На чаепитие'), ('birthday', 'На день рождения'), ('wedding', 'На свадьбу')], max_length=50, null=True, verbose_name='Причина'),
        ),
    ]
