# Generated by Django 5.1 on 2024-08-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0007_order_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
