# Generated by Django 5.1 on 2024-08-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0008_order_courier_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='courier_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий курьеру'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('payment', 'В оплате'), ('delivery', 'В доставке'), ('complete', 'Завершен')], max_length=50, verbose_name='Статус заказа'),
        ),
    ]
