# Generated by Django 5.1 on 2024-08-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_name_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='adderss', max_length=200, verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
